use crate::ast::NameId;
use crate::mir::dumper::{MirDumpConfig, MirDumper};
use crate::mir::{MirModuleId, MirType};

#[test]
fn test_dump_basic_module() {
    let mut builder = crate::mir::MirBuilder::new(MirModuleId::new(1).unwrap(), 8);

    // Types
    let i32_ty = builder.add_type(MirType::I32);
    let f32_ty = builder.add_type(MirType::F32);
    let void_ty = builder.add_type(MirType::Void);
    let ptr_ty = builder.add_type(MirType::Pointer { pointee: i32_ty });

    // Global
    let global_id = builder.create_global_with_init(NameId::new("g_val"), i32_ty, false, None);

    // Function
    let func_id = builder.define_function(
        NameId::new("test_func"),
        vec![i32_ty],
        void_ty,
        false,
        crate::mir::MirLinkage::External,
    );
    builder.set_current_function(func_id);

    let block_id = builder.create_block();
    builder.set_function_entry_block(func_id, block_id);
    builder.set_current_block(block_id);

    // Locals
    let loc_i32 = builder.create_local(Some(NameId::new("loc_i32")), i32_ty, false);
    let loc_f32 = builder.create_local(Some(NameId::new("loc_f32")), f32_ty, false);
    let loc_ptr = builder.create_local(Some(NameId::new("loc_ptr")), ptr_ty, false);

    // Some instructions
    use crate::mir::{MirStmt, Operand, Place, Rvalue, Terminator};

    let const_val_id = builder.create_constant(i32_ty, crate::mir::ConstValueKind::Int(42));
    builder.add_statement(MirStmt::Assign(
        Place::Local(loc_i32),
        Rvalue::Use(Operand::Constant(const_val_id)),
    ));

    builder.add_statement(MirStmt::Store(
        Operand::Copy(Box::new(Place::Local(loc_i32))),
        Place::Global(global_id),
    ));

    builder.set_terminator(Terminator::Return(None));

    let mir = builder.consume();
    let config = MirDumpConfig::default();
    let dumper = MirDumper::new(&mir, &config);
    let output = dumper.generate_mir_dump().unwrap();

    insta::assert_snapshot!(output, @r"
    ; MIR Dump for Module 1
    ; Generated by Cendol C11 Compiler

    type %t0 = i32
    type %t1 = f32
    type %t2 = void
    type %t3 = ptr<%t0>

    global @g_val: i32

    fn test_func(%param0: i32) -> void
    {
      locals {
        %loc_i32: i32
        %loc_f32: f32
        %loc_ptr: ptr<i32>
      }

      bb1:
        %loc_i32 = const 42
        store %loc_i32, @g_val
        return
    }
    ");
}

#[test]
fn test_dump_complex_types() {
    let mut builder = crate::mir::MirBuilder::new(MirModuleId::new(1).unwrap(), 8);
    let i32_ty = builder.add_type(MirType::I32);

    // Array
    use crate::mir::{MirArrayLayout, MirRecordLayout};
    let array_layout = MirArrayLayout {
        size: 40,
        align: 4,
        stride: 4,
    };
    let array_ty = builder.add_type(MirType::Array {
        element: i32_ty,
        size: 10,
        layout: array_layout,
    });

    // Struct
    let record_layout = MirRecordLayout {
        size: 8,
        alignment: 4,
        field_offsets: vec![0, 4],
    };
    let struct_ty = builder.add_type(MirType::Record {
        name: NameId::new("MyStruct"),
        field_types: vec![i32_ty, i32_ty],
        field_names: vec![NameId::new("a"), NameId::new("b")],
        is_union: false,
        layout: record_layout,
    });

    // Function type
    let func_ty = builder.add_type(MirType::Function {
        return_type: i32_ty,
        params: vec![i32_ty, i32_ty],
        is_variadic: false,
    });

    let mir = builder.consume();
    let config = MirDumpConfig::default();
    let dumper = MirDumper::new(&mir, &config);
    let output = dumper.generate_mir_dump().unwrap();

    insta::assert_snapshot!(output, @r"
    ; MIR Dump for Module 1
    ; Generated by Cendol C11 Compiler

    type %t0 = i32
    type %t1 = [10]%t0
    type %t2 = struct MyStruct { a: %t0, b: %t0 }
    type %t3 = fn(%t0, %t0) -> %t0

    ");
}
