use crate::ast::NameId;
use crate::mir::MirType;
use crate::mir::dumper::{MirDumpConfig, MirDumper};

#[test]
fn test_dump_basic_module() {
    let mut builder = crate::mir::MirBuilder::new(8);

    // Types
    let i32_ty = builder.add_type(MirType::I32);
    let void_ty = builder.add_type(MirType::Void);

    // Global
    let global_id = builder.create_global(crate::mir::GlobalDecl::new(
        NameId::new("g_val"),
        i32_ty,
        crate::mir::MirLinkage::External,
    ));

    // Function
    let func_id = builder.define_function(
        NameId::new("test_func"),
        vec![i32_ty],
        void_ty,
        false,
        crate::mir::MirLinkage::External,
    );
    builder.set_current_function(func_id);

    let block_id = builder.create_block();
    builder.set_function_entry_block(func_id, block_id);
    builder.set_current_block(block_id);

    // Locals
    let loc_i32 = builder.create_local(Some(NameId::new("loc_i32")), i32_ty, false);

    // Some instructions
    use crate::mir::{MirStmt, Operand, Place, Rvalue, Terminator};

    let const_val_id = builder.create_constant(i32_ty, crate::mir::ConstValueKind::Int(42));
    builder.add_stmt(MirStmt::Assign(
        Place::Local(loc_i32),
        Rvalue::Use(Operand::Constant(const_val_id)),
    ));

    builder.add_stmt(MirStmt::Assign(
        Place::Global(global_id),
        Rvalue::Use(Operand::Copy(Box::new(Place::Local(loc_i32)))),
    ));

    builder.set_terminator(Terminator::Return(None));

    let mir = builder.consume();
    let config = MirDumpConfig::default();
    let dumper = MirDumper::new(&mir, &config);
    let output = dumper.generate_mir_dump().unwrap();

    insta::assert_snapshot!(output, @"
    ; MIR Dump for Module 1
    ; Generated by Cendol C11 Compiler

    type %t0 = i32
    type %t1 = void

    global @g_val: i32

    fn test_func(%param0: i32) -> void
    {
      locals {
        %loc_i32: i32
      }

      bb1:
        %loc_i32 = const 42
        @g_val = %loc_i32
        return
    }
    ");
}
