use crate::ast::literal::{IntSuffix, LitRef};
use crate::parser::lexer::TokenKind;

#[test]
fn test_token_kind_display() {
    assert_eq!(
        TokenKind::Literal(LitRef::from_int(0, IntSuffix::None, 10)).display(),
        "literal"
    );
    assert_eq!(TokenKind::Auto.display(), "auto");
    assert_eq!(TokenKind::Extern.display(), "extern");
    assert_eq!(TokenKind::Register.display(), "register");
    assert_eq!(TokenKind::Static.display(), "static");
    assert_eq!(TokenKind::ThreadLocal.display(), "_Thread_local");
    assert_eq!(TokenKind::Constexpr.display(), "constexpr");
    assert_eq!(TokenKind::Const.display(), "const");
    assert_eq!(TokenKind::Restrict.display(), "restrict");
    assert_eq!(TokenKind::Volatile.display(), "volatile");
    assert_eq!(TokenKind::Atomic.display(), "_Atomic");
    assert_eq!(TokenKind::Bool.display(), "_Bool");
    assert_eq!(TokenKind::Char.display(), "char");
    assert_eq!(TokenKind::Char8.display(), "char8_t");
    assert_eq!(TokenKind::Double.display(), "double");
    assert_eq!(TokenKind::Float.display(), "float");
    assert_eq!(TokenKind::Int.display(), "int");
    assert_eq!(TokenKind::Long.display(), "long");
    assert_eq!(TokenKind::Short.display(), "short");
    assert_eq!(TokenKind::Signed.display(), "signed");
    assert_eq!(TokenKind::Unsigned.display(), "unsigned");
    assert_eq!(TokenKind::Void.display(), "void");
    assert_eq!(TokenKind::Complex.display(), "_Complex");
    assert_eq!(TokenKind::Struct.display(), "struct");
    assert_eq!(TokenKind::Union.display(), "union");
    assert_eq!(TokenKind::Enum.display(), "enum");
    assert_eq!(TokenKind::Break.display(), "break");
    assert_eq!(TokenKind::Case.display(), "case");
    assert_eq!(TokenKind::Continue.display(), "continue");
    assert_eq!(TokenKind::Default.display(), "default");
    assert_eq!(TokenKind::Do.display(), "do");
    assert_eq!(TokenKind::Else.display(), "else");
    assert_eq!(TokenKind::For.display(), "for");
    assert_eq!(TokenKind::Goto.display(), "goto");
    assert_eq!(TokenKind::If.display(), "if");
    assert_eq!(TokenKind::Return.display(), "return");
    assert_eq!(TokenKind::Switch.display(), "switch");
    assert_eq!(TokenKind::While.display(), "while");
    assert_eq!(TokenKind::Alignas.display(), "_Alignas");
    assert_eq!(TokenKind::Alignof.display(), "_Alignof");
    assert_eq!(TokenKind::Generic.display(), "_Generic");
    assert_eq!(TokenKind::Inline.display(), "inline");
    assert_eq!(TokenKind::Noreturn.display(), "_Noreturn");
    assert_eq!(TokenKind::Pragma.display(), "_Pragma");
    assert_eq!(TokenKind::Sizeof.display(), "sizeof");
    assert_eq!(TokenKind::StaticAssert.display(), "_Static_assert");
    assert_eq!(TokenKind::Typedef.display(), "typedef");
    assert_eq!(TokenKind::Typeof.display(), "typeof");
    assert_eq!(TokenKind::TypeofUnqual.display(), "typeof_unqual");
    assert_eq!(TokenKind::Real.display(), "__real__");
    assert_eq!(TokenKind::Imag.display(), "__imag__");
    assert_eq!(TokenKind::Attribute.display(), "__attribute__");
    assert_eq!(TokenKind::BuiltinVaArg.display(), "__builtin_va_arg");
    assert_eq!(TokenKind::BuiltinBitCast.display(), "__builtin_bit_cast");
    assert_eq!(TokenKind::BuiltinConvertVector.display(), "__builtin_convertvector");
    assert_eq!(TokenKind::BuiltinVaList.display(), "__builtin_va_list");
    assert_eq!(TokenKind::BuiltinChooseExpr.display(), "__builtin_choose_expr");
    assert_eq!(TokenKind::BuiltinComplex.display(), "__builtin_complex");
    assert_eq!(TokenKind::BuiltinOffsetof.display(), "__builtin_offsetof");
    assert_eq!(
        TokenKind::BuiltinTypesCompatibleP.display(),
        "__builtin_types_compatible_p"
    );
    assert_eq!(TokenKind::Asm.display(), "asm");
    assert_eq!(TokenKind::AutoType.display(), "__auto_type");
    assert_eq!(TokenKind::PrettyFunction.display(), "__PRETTY_FUNCTION__");
    assert_eq!(TokenKind::Plus.display(), "+");
    assert_eq!(TokenKind::Minus.display(), "-");
    assert_eq!(TokenKind::Star.display(), "*");
    assert_eq!(TokenKind::Slash.display(), "/");
    assert_eq!(TokenKind::Percent.display(), "%");
    assert_eq!(TokenKind::Increment.display(), "++");
    assert_eq!(TokenKind::Decrement.display(), "--");
    assert_eq!(TokenKind::And.display(), "&");
    assert_eq!(TokenKind::Or.display(), "|");
    assert_eq!(TokenKind::Xor.display(), "^");
    assert_eq!(TokenKind::Not.display(), "!");
    assert_eq!(TokenKind::Tilde.display(), "~");
    assert_eq!(TokenKind::LeftShift.display(), "<<");
    assert_eq!(TokenKind::RightShift.display(), ">>");
    assert_eq!(TokenKind::Less.display(), "<");
    assert_eq!(TokenKind::Greater.display(), ">");
    assert_eq!(TokenKind::LessEqual.display(), "<=");
    assert_eq!(TokenKind::GreaterEqual.display(), ">=");
    assert_eq!(TokenKind::Equal.display(), "==");
    assert_eq!(TokenKind::NotEqual.display(), "!=");
    assert_eq!(TokenKind::Assign.display(), "=");
    assert_eq!(TokenKind::PlusAssign.display(), "+=");
    assert_eq!(TokenKind::MinusAssign.display(), "-=");
    assert_eq!(TokenKind::StarAssign.display(), "*=");
    assert_eq!(TokenKind::DivAssign.display(), "/=");
    assert_eq!(TokenKind::ModAssign.display(), "%=");
    assert_eq!(TokenKind::AndAssign.display(), "&=");
    assert_eq!(TokenKind::OrAssign.display(), "|=");
    assert_eq!(TokenKind::XorAssign.display(), "^=");
    assert_eq!(TokenKind::LeftShiftAssign.display(), "<<=");
    assert_eq!(TokenKind::RightShiftAssign.display(), ">>=");
    assert_eq!(TokenKind::LogicAnd.display(), "&&");
    assert_eq!(TokenKind::LogicOr.display(), "||");
    assert_eq!(TokenKind::Arrow.display(), "->");
    assert_eq!(TokenKind::Dot.display(), ".");
    assert_eq!(TokenKind::Question.display(), "?");
    assert_eq!(TokenKind::Colon.display(), ":");
    assert_eq!(TokenKind::Comma.display(), ",");
    assert_eq!(TokenKind::Semicolon.display(), ";");
    assert_eq!(TokenKind::Ellipsis.display(), "...");
    assert_eq!(TokenKind::LeftParen.display(), "(");
    assert_eq!(TokenKind::RightParen.display(), ")");
    assert_eq!(TokenKind::LeftBracket.display(), "[");
    assert_eq!(TokenKind::RightBracket.display(), "]");
    assert_eq!(TokenKind::LeftBrace.display(), "{");
    assert_eq!(TokenKind::RightBrace.display(), "}");
    assert_eq!(TokenKind::EndOfFile.display(), "end of file");
}
