//! MIR (Mid-level Intermediate Representation) Dumper
//!
//! This module provides functionality to dump MIR in a human-readable format
//! following the C11 compiler's specific conventions:
//! - Local variables: %0, %1, %tmp3
//! - Global variables: @g_var
//! - Basic blocks: bb0, bb1
//! - Constants: const 42, const null
//! - Types: i8, i16, i32, i64, u8, u16, u32, u64, f32, f64, ptr<T>

use std::fmt;
use std::fmt::Write;

use super::{
    BinaryFloatOp, CallTarget, ConstValueId, ConstValueKind, Global, GlobalId, LocalId, MirBlock, MirBlockId,
    MirFunction, MirFunctionId, MirLinkage, MirStmt, MirType, Operand, Place, Rvalue, Terminator, TypeId, UnaryFloatOp,
};
use crate::mir::MirProgram;

/// Configuration for MIR dump output
#[derive(Debug, Clone)]
pub(crate) struct MirDumpConfig {
    pub include_header: bool,
}

impl Default for MirDumpConfig {
    fn default() -> Self {
        MirDumpConfig { include_header: true }
    }
}

/// Main MIR dumper that generates human-readable MIR output
pub(crate) struct MirDumper<'a> {
    mir: &'a MirProgram,
    config: &'a MirDumpConfig,
}

impl<'a> MirDumper<'a> {
    /// Create a new MIR dumper
    pub(crate) fn new(mir: &'a MirProgram, config: &'a MirDumpConfig) -> Self {
        Self { mir, config }
    }

    /// Generate the complete MIR dump
    pub(crate) fn generate_mir_dump(&self) -> Result<String, fmt::Error> {
        let mut output = String::new();

        // Dump module header
        if self.config.include_header {
            writeln!(output, "; MIR Dump for Module 1")?;
            writeln!(output, "; Generated by Cendol C11 Compiler")?;
            writeln!(output)?;
        }

        // Dump type definitions
        self.dump_types(&mut output)?;
        writeln!(output)?;

        // Dump global variables first
        if !self.mir.globals.is_empty() {
            for global in self.mir.globals.iter() {
                self.dump_global(&mut output, global)?;
                writeln!(output)?;
            }
            writeln!(output)?;
        }

        // Dump all functions
        for func in self.mir.functions.iter() {
            self.dump_function(&mut output, func)?;
            writeln!(output)?;
        }

        Ok(output)
    }

    /// Dump a single function
    fn dump_function(&self, output: &mut String, func: &MirFunction) -> fmt::Result {
        // Function signature
        let fn_keyword = if matches!(func.linkage, MirLinkage::Import) {
            "extern fn"
        } else {
            "fn"
        };
        write!(output, "{} {}(", fn_keyword, func.name)?;

        // Dump parameters
        for (i, &param_id) in func.params.iter().enumerate() {
            if i > 0 {
                write!(output, ", ")?;
            }
            if let Some(param) = self.mir.locals.get(param_id.index()) {
                write!(output, "%")?;
                if let Some(name) = &param.name {
                    write!(output, "{}", name)?;
                } else {
                    write!(output, "unnamed")?;
                }
                write!(output, ": ")?;
                self.write_type(output, param.type_id)?;
            } else {
                write!(output, "%param{}: ?", param_id.get())?;
            }
        }

        if func.is_variadic {
            if !func.params.is_empty() {
                write!(output, ", ")?;
            }
            write!(output, "...")?;
        }

        write!(output, ") -> ")?;
        self.write_type(output, func.return_type)?;

        // For extern functions, don't output any body
        if matches!(func.linkage, MirLinkage::Import) {
            writeln!(output)?;
            return Ok(());
        }

        writeln!(output)?;

        // Function body
        writeln!(output, "{{")?;

        // Dump locals section
        if !func.locals.is_empty() {
            writeln!(output, "  locals {{")?;
            for &local_id in &func.locals {
                if let Some(local) = self.mir.locals.get(local_id.index()) {
                    write!(output, "    ")?;
                    write!(output, "%")?;
                    if let Some(name) = &local.name {
                        write!(output, "{}", name)?;
                    } else {
                        write!(output, "{}", local_id.get())?;
                    }
                    write!(output, ": ")?;
                    self.write_type(output, local.type_id)?;
                    writeln!(output)?;
                }
            }
            writeln!(output, "  }}")?;
        }

        // Dump basic blocks
        for &block_id in &func.blocks {
            if let Some(block) = self.mir.blocks.get(block_id.index()) {
                self.dump_block(output, block_id, block)?;
            }
        }

        writeln!(output, "}}")
    }

    /// Dump all type definitions
    fn dump_types(&self, output: &mut String) -> fmt::Result {
        for (i, mir_type) in self.mir.module.types.iter().enumerate() {
            let type_id = TypeId::new((i + 1) as u32).unwrap();
            let type_index = self.get_type_index_from_type_id(type_id);
            write!(output, "type %t{} = ", type_index)?;
            self.write_type_inner(output, type_id, mir_type, true)?;
            writeln!(output)?;
        }
        Ok(())
    }

    /// Internal helper to format MIR types
    fn write_type_inner<W: fmt::Write>(
        &self,
        output: &mut W,
        type_id: TypeId,
        mir_type: &MirType,
        is_definition: bool,
    ) -> fmt::Result {
        match mir_type {
            MirType::Void => write!(output, "void"),
            MirType::Bool => write!(output, "bool"),
            MirType::I8 => write!(output, "i8"),
            MirType::I16 => write!(output, "i16"),
            MirType::I32 => write!(output, "i32"),
            MirType::I64 => write!(output, "i64"),
            MirType::U8 => write!(output, "u8"),
            MirType::U16 => write!(output, "u16"),
            MirType::U32 => write!(output, "u32"),
            MirType::U64 => write!(output, "u64"),
            MirType::F32 => write!(output, "f32"),
            MirType::F64 => write!(output, "f64"),
            MirType::F80 => write!(output, "f80"),
            MirType::F128 => write!(output, "f128"),
            MirType::Pointer { pointee } => {
                if is_definition {
                    let index = self.get_type_index_from_type_id(*pointee);
                    write!(output, "ptr<%t{}>", index)
                } else {
                    write!(output, "ptr<")?;
                    self.write_type(output, *pointee)?;
                    write!(output, ">")
                }
            }
            MirType::Array { element, size, .. } => {
                if is_definition {
                    let index = self.get_type_index_from_type_id(*element);
                    write!(output, "[{}]%t{}", size, index)
                } else {
                    write!(output, "[{}]", size)?;
                    self.write_type(output, *element)
                }
            }
            MirType::Function {
                return_type,
                params,
                is_variadic,
            } => {
                write!(output, "fn(")?;
                for (i, &p) in params.iter().enumerate() {
                    if i > 0 {
                        write!(output, ", ")?;
                    }
                    if is_definition {
                        let index = self.get_type_index_from_type_id(p);
                        write!(output, "%t{}", index)?;
                    } else {
                        self.write_type(output, p)?;
                    }
                }
                if *is_variadic {
                    if !params.is_empty() {
                        write!(output, ", ")?;
                    }
                    write!(output, "...")?;
                }
                write!(output, ") -> ")?;
                if is_definition {
                    let index = self.get_type_index_from_type_id(*return_type);
                    write!(output, "%t{}", index)
                } else {
                    self.write_type(output, *return_type)
                }
            }
            MirType::Record {
                name,
                field_types,
                field_names,
                is_union,
                ..
            } => {
                if is_definition {
                    let kind = if *is_union { "union" } else { "struct" };
                    write!(output, "{} {} {{ ", kind, name)?;
                    for (i, (fname, fid)) in field_names.iter().zip(field_types.iter()).enumerate() {
                        if i > 0 {
                            write!(output, ", ")?;
                        }
                        let index = self.get_type_index_from_type_id(*fid);
                        write!(output, "{}: %t{}", fname, index)?;
                    }
                    write!(output, " }}")
                } else {
                    let index = self.get_type_index_from_type_id(type_id);
                    write!(output, "%t{}", index)
                }
            }
        }
    }

    /// Helper function to get type index from TypeId
    fn get_type_index_from_type_id(&self, type_id: TypeId) -> usize {
        // Fallback: assume sequential mapping
        (type_id.get() - 1) as usize
    }

    /// Dump a single global variable
    fn dump_global(&self, output: &mut String, global: &Global) -> fmt::Result {
        write!(output, "global @{}: ", global.name)?;
        self.write_type(output, global.type_id)?;
        if global.is_tls {
            write!(output, " (tls)")?;
        }

        if let Some(const_id) = global.initial_value {
            write!(output, " = ")?;
            if !self.write_string_literal_if_possible(output, global.name.as_str(), const_id)? {
                self.write_const(output, const_id)?;
            }
        }
        Ok(())
    }

    /// Dump a basic block
    fn dump_block(&self, output: &mut String, block_id: MirBlockId, block: &MirBlock) -> fmt::Result {
        writeln!(output)?;
        write!(output, "  ")?;
        self.write_block(output, block_id)?;
        writeln!(output, ":")?;

        // Dump statements in the block
        for &stmt_id in &block.statements {
            if let Some(stmt) = self.mir.statements.get(stmt_id.index()) {
                write!(output, "    ")?;
                self.dump_statement(output, stmt)?;
                writeln!(output)?;
            }
        }

        // Dump terminator (MUST be explicit)
        write!(output, "    ")?;
        self.dump_terminator(output, &block.terminator)?;
        writeln!(output)
    }

    /// Dump a statement
    fn dump_statement(&self, output: &mut String, stmt: &MirStmt) -> fmt::Result {
        match stmt {
            MirStmt::Assign(place, rvalue) => {
                self.write_place(output, place)?;
                write!(output, " = ")?;
                self.dump_rvalue(output, rvalue)
            }
            MirStmt::Call { target, args, dest } => {
                if let Some(place) = dest {
                    self.write_place(output, place)?;
                    write!(output, " = ")?;
                }
                write!(output, "call ")?;
                self.write_call_target(output, target)?;
                write!(output, "(")?;
                for (i, operand) in args.iter().enumerate() {
                    if i > 0 {
                        write!(output, ", ")?;
                    }
                    self.write_operand(output, operand)?;
                }
                write!(output, ")")
            }
            MirStmt::BuiltinVaStart(ap, last) => {
                write!(output, "va_start(")?;
                self.write_place(output, ap)?;
                write!(output, ", ")?;
                self.write_operand(output, last)?;
                write!(output, ")")
            }
            MirStmt::BuiltinVaEnd(ap) => {
                write!(output, "va_end(")?;
                self.write_place(output, ap)?;
                write!(output, ")")
            }
            MirStmt::BuiltinVaCopy(dst, src) => {
                write!(output, "va_copy(")?;
                self.write_place(output, dst)?;
                write!(output, ", ")?;
                self.write_place(output, src)?;
                write!(output, ")")
            }
            MirStmt::AtomicStore(ptr, val, order) => {
                write!(output, "atomic_store(")?;
                self.write_operand(output, ptr)?;
                write!(output, ", ")?;
                self.write_operand(output, val)?;
                write!(output, ", {:?})", order)
            }
        }
    }

    /// Dump a terminator
    fn dump_terminator(&self, output: &mut String, terminator: &Terminator) -> fmt::Result {
        match terminator {
            Terminator::Goto(block_id) => {
                write!(output, "br ")?;
                self.write_block(output, *block_id)
            }
            Terminator::If(cond, then_block, else_block) => {
                write!(output, "cond_br ")?;
                self.write_operand(output, cond)?;
                write!(output, ", ")?;
                self.write_block(output, *then_block)?;
                write!(output, ", ")?;
                self.write_block(output, *else_block)
            }
            Terminator::Return(operand) => {
                write!(output, "return")?;
                if let Some(op) = operand {
                    write!(output, " ")?;
                    self.write_operand(output, op)?;
                }
                Ok(())
            }
            Terminator::Unreachable => write!(output, "unreachable"),
            Terminator::Trap => write!(output, "trap"),
        }
    }

    /// Convert MIR type to string representation
    fn write_type<W: fmt::Write>(&self, output: &mut W, type_id: TypeId) -> fmt::Result {
        if let Some(mir_type) = self.mir.types.get(type_id.index()) {
            self.write_type_inner(output, type_id, mir_type, false)
        } else {
            write!(output, "unknown_type_{}", type_id.get())
        }
    }

    /// Convert local ID to string representation
    fn write_local<W: fmt::Write>(&self, output: &mut W, local_id: LocalId) -> fmt::Result {
        write!(output, "%")?;
        let local = self.mir.locals.get(local_id.index());
        match local {
            Some(local) if local.name.is_some() => write!(output, "{}", local.name.as_ref().unwrap()),
            _ => write!(output, "{}", local_id.get()),
        }
    }

    /// Convert global ID to string representation
    fn write_global<W: fmt::Write>(&self, output: &mut W, global_id: GlobalId) -> fmt::Result {
        if let Some(global) = self.mir.globals.get(global_id.index()) {
            write!(output, "@{}", global.name)
        } else {
            write!(output, "@global_{}", global_id.get())
        }
    }

    /// Convert block ID to string representation
    fn write_block<W: fmt::Write>(&self, output: &mut W, block_id: MirBlockId) -> fmt::Result {
        write!(output, "bb{}", block_id.get())
    }

    /// Convert function ID to string representation
    fn write_function_name<W: fmt::Write>(&self, output: &mut W, func_id: MirFunctionId) -> fmt::Result {
        if let Some(func) = self.mir.functions.get(func_id.index()) {
            write!(output, "{}", func.name)
        } else {
            write!(output, "func_{}", func_id.get())
        }
    }

    /// Convert call target to string representation
    fn write_call_target<W: fmt::Write>(&self, output: &mut W, call_target: &CallTarget) -> fmt::Result {
        match call_target {
            CallTarget::Direct(func_id) => self.write_function_name(output, *func_id),
            CallTarget::Indirect(operand) => {
                write!(output, "*")?;
                self.write_operand(output, operand)
            }
        }
    }

    /// Try to format a constant as a string literal if applicable
    fn write_string_literal_if_possible<W: fmt::Write>(
        &self,
        output: &mut W,
        global_name: &str,
        const_id: ConstValueId,
    ) -> Result<bool, fmt::Error> {
        if !global_name.starts_with(".L.str") {
            return Ok(false);
        }

        if let Some(const_value) = self.mir.constants.get(const_id.index())
            && let ConstValueKind::ArrayLiteral(elements) = &const_value.kind
        {
            // First, check if all elements are integers (bytes)
            for &element_id in elements {
                let element = self.mir.constants.get(element_id.index()).unwrap();
                if !matches!(element.kind, ConstValueKind::Int(_)) {
                    return Ok(false);
                }
            }

            write!(output, "const \"")?;
            for &element_id in elements {
                let element = self.mir.constants.get(element_id.index()).unwrap();
                if let ConstValueKind::Int(byte) = &element.kind {
                    let byte = *byte as u8;
                    if byte == 0 {
                        break;
                    }

                    match byte {
                        b'\n' => write!(output, "\\n")?,
                        b'\r' => write!(output, "\\r")?,
                        b'\t' => write!(output, "\\t")?,
                        b'\\' => write!(output, "\\\\")?,
                        b'"' => write!(output, "\\\"")?,
                        b if (32..=126).contains(&b) => write!(output, "{}", byte as char)?,
                        _ => write!(output, "\\x{:02x}", byte)?,
                    }
                }
            }
            write!(output, "\"")?;
            return Ok(true);
        }

        Ok(false)
    }

    /// Convert constant ID to string representation
    fn write_const<W: fmt::Write>(&self, output: &mut W, const_id: ConstValueId) -> fmt::Result {
        if let Some(const_value) = self.mir.constants.get(const_id.index()) {
            match &const_value.kind {
                ConstValueKind::Int(val) => write!(output, "const {}", val),
                ConstValueKind::Float(val) => write!(output, "const {}", val),
                ConstValueKind::Bool(val) => write!(output, "const {}", val),
                ConstValueKind::Null => write!(output, "const null"),
                ConstValueKind::Zero => write!(output, "const zero"),
                ConstValueKind::StructLiteral(fields) => {
                    // Expand struct literal to show field contents
                    write!(output, "const struct_literal {{ ")?;
                    for (i, (field_idx, field_const_id)) in fields.iter().enumerate() {
                        if i > 0 {
                            write!(output, ", ")?;
                        }
                        write!(output, "{}: ", field_idx)?;
                        self.write_const(output, *field_const_id)?;
                    }
                    write!(output, " }}")
                }
                ConstValueKind::ArrayLiteral(elements) => {
                    // Expand array literal to show element contents
                    write!(output, "const array_literal [")?;
                    for (i, element_const_id) in elements.iter().enumerate() {
                        if i > 0 {
                            write!(output, ", ")?;
                        }
                        self.write_const(output, *element_const_id)?;
                    }
                    write!(output, "]")
                }
                ConstValueKind::GlobalAddress(global_id, addend) => {
                    write!(output, "const ")?;
                    self.write_global(output, *global_id)?;
                    if *addend != 0 {
                        write!(output, "+{}", addend)
                    } else {
                        Ok(())
                    }
                }
                ConstValueKind::FunctionAddress(func_id) => {
                    write!(output, "const ")?;
                    self.write_function_name(output, *func_id)
                }
            }
        } else {
            write!(output, "const unknown_{}", const_id.get())
        }
    }

    /// Convert place to string representation
    fn write_place<W: fmt::Write>(&self, output: &mut W, place: &Place) -> fmt::Result {
        match place {
            Place::Local(local_id) => self.write_local(output, *local_id),
            Place::Deref(operand) => {
                write!(output, "deref(")?;
                self.write_operand(output, operand)?;
                write!(output, ")")
            }
            Place::Global(global_id) => self.write_global(output, *global_id),
            Place::StructField(base_place, field_idx, bit_info) => {
                self.write_place(output, base_place)?;
                write!(output, ".field_{}", field_idx)?;
                if let Some(b) = bit_info {
                    write!(output, " (bit:{}:{})", b.offset, b.width)?;
                }
                Ok(())
            }
            Place::ArrayIndex(base_place, index) => {
                self.write_place(output, base_place)?;
                write!(output, "[")?;
                self.write_operand(output, index)?;
                write!(output, "]")
            }
        }
    }

    /// Convert operand to string representation
    fn write_operand<W: fmt::Write>(&self, output: &mut W, operand: &Operand) -> fmt::Result {
        match operand {
            Operand::Copy(place) => self.write_place(output, place),
            Operand::Constant(const_id) => self.write_const(output, *const_id),
            Operand::AddressOf(place) => {
                write!(output, "addr_of(")?;
                self.write_place(output, place)?;
                write!(output, ")")
            }
            Operand::Cast(type_id, operand) => {
                write!(output, "cast<")?;
                self.write_type(output, *type_id)?;
                write!(output, ">(")?;
                self.write_operand(output, operand)?;
                write!(output, ")")
            }
        }
    }

    /// Dump an rvalue (for use in assignments)
    fn dump_rvalue(&self, output: &mut String, rvalue: &Rvalue) -> fmt::Result {
        match rvalue {
            Rvalue::Use(operand) => self.write_operand(output, operand),
            Rvalue::BinaryIntOp(op, left, right) => {
                self.write_operand(output, left)?;
                write!(output, " {} ", self.binary_int_op_to_string(op))?;
                self.write_operand(output, right)
            }
            Rvalue::BinaryFloatOp(op, left, right) => {
                self.write_operand(output, left)?;
                write!(output, " {} ", self.binary_float_op_to_string(op))?;
                self.write_operand(output, right)
            }
            Rvalue::UnaryIntOp(op, operand) => {
                write!(output, "{} ", self.unary_int_op_to_string(op))?;
                self.write_operand(output, operand)
            }
            Rvalue::UnaryFloatOp(op, operand) => {
                write!(output, "{} ", self.unary_float_op_to_string(op))?;
                self.write_operand(output, operand)
            }
            Rvalue::PtrAdd(base, offset) => {
                write!(output, "ptradd(")?;
                self.write_operand(output, base)?;
                write!(output, ", ")?;
                self.write_operand(output, offset)?;
                write!(output, ")")
            }
            Rvalue::PtrSub(base, offset) => {
                write!(output, "ptrsub(")?;
                self.write_operand(output, base)?;
                write!(output, ", ")?;
                self.write_operand(output, offset)?;
                write!(output, ")")
            }
            Rvalue::PtrDiff(left, right) => {
                write!(output, "ptrdiff(")?;
                self.write_operand(output, left)?;
                write!(output, ", ")?;
                self.write_operand(output, right)?;
                write!(output, ")")
            }
            Rvalue::StructLiteral(fields) => {
                write!(output, "struct{{")?;
                for (i, (idx, op)) in fields.iter().enumerate() {
                    if i > 0 {
                        write!(output, ", ")?;
                    }
                    write!(output, "{}: ", idx)?;
                    self.write_operand(output, op)?;
                }
                write!(output, "}}")
            }
            Rvalue::ArrayLiteral(elements) => {
                write!(output, "[")?;
                for (i, op) in elements.iter().enumerate() {
                    if i > 0 {
                        write!(output, ", ")?;
                    }
                    self.write_operand(output, op)?;
                }
                write!(output, "]")
            }
            Rvalue::BuiltinVaArg(ap, ty) => {
                write!(output, "va_arg(")?;
                self.write_place(output, ap)?;
                write!(output, ", ")?;
                self.write_type(output, *ty)?;
                write!(output, ")")
            }
            Rvalue::AtomicLoad(ptr, order) => {
                write!(output, "atomic_load(")?;
                self.write_operand(output, ptr)?;
                write!(output, ", {:?})", order)
            }
            Rvalue::AtomicExchange(ptr, val, order) => {
                write!(output, "atomic_xchg(")?;
                self.write_operand(output, ptr)?;
                write!(output, ", ")?;
                self.write_operand(output, val)?;
                write!(output, ", {:?})", order)
            }
            Rvalue::AtomicCompareExchange(ptr, expected, desired, weak, success, failure) => {
                write!(output, "atomic_cmpxchg(")?;
                self.write_operand(output, ptr)?;
                write!(output, ", ")?;
                self.write_operand(output, expected)?;
                write!(output, ", ")?;
                self.write_operand(output, desired)?;
                write!(output, ", {}, {:?}, {:?})", weak, success, failure)
            }
            Rvalue::AtomicFetchOp(op, ptr, val, order) => {
                write!(output, "atomic_fetch_{}(", self.binary_int_op_to_string(op))?;
                self.write_operand(output, ptr)?;
                write!(output, ", ")?;
                self.write_operand(output, val)?;
                write!(output, ", {:?})", order)
            }
        }
    }

    /// Convert integer binary operation to string representation
    fn binary_int_op_to_string(&self, op: &super::BinaryIntOp) -> &'static str {
        match op {
            super::BinaryIntOp::Add => "+",
            super::BinaryIntOp::Sub => "-",
            super::BinaryIntOp::Mul => "*",
            super::BinaryIntOp::Div => "/",
            super::BinaryIntOp::Mod => "%",
            super::BinaryIntOp::BitAnd => "&",
            super::BinaryIntOp::BitOr => "|",
            super::BinaryIntOp::BitXor => "^",
            super::BinaryIntOp::LShift => "<<",
            super::BinaryIntOp::RShift => ">>",
            super::BinaryIntOp::Eq => "==",
            super::BinaryIntOp::Ne => "!=",
            super::BinaryIntOp::Lt => "<",
            super::BinaryIntOp::Le => "<=",
            super::BinaryIntOp::Gt => ">",
            super::BinaryIntOp::Ge => ">=",
        }
    }

    /// Convert integer unary operation to string representation
    fn unary_int_op_to_string(&self, op: &super::UnaryIntOp) -> &'static str {
        match op {
            super::UnaryIntOp::Neg => "-",
            super::UnaryIntOp::BitwiseNot => "~",
            super::UnaryIntOp::LogicalNot => "!",
            super::UnaryIntOp::Popcount => "popcount",
            super::UnaryIntOp::Clz => "clz",
            super::UnaryIntOp::Ctz => "ctz",
            super::UnaryIntOp::Bswap16 => "bswap16",
            super::UnaryIntOp::Bswap32 => "bswap32",
            super::UnaryIntOp::Bswap64 => "bswap64",
            super::UnaryIntOp::Ffs => "ffs",
        }
    }

    /// Convert floating-point binary operation to string representation
    fn binary_float_op_to_string(&self, op: &BinaryFloatOp) -> &'static str {
        match op {
            BinaryFloatOp::Add => "fadd",
            BinaryFloatOp::Sub => "fsub",
            BinaryFloatOp::Mul => "fmul",
            BinaryFloatOp::Div => "fdiv",
            BinaryFloatOp::Eq => "feq",
            BinaryFloatOp::Ne => "fne",
            BinaryFloatOp::Lt => "flt",
            BinaryFloatOp::Le => "fle",
            BinaryFloatOp::Gt => "fgt",
            BinaryFloatOp::Ge => "fge",
        }
    }

    /// Convert floating-point unary operation to string representation
    fn unary_float_op_to_string(&self, op: &UnaryFloatOp) -> &'static str {
        match op {
            UnaryFloatOp::Neg => "fneg",
            UnaryFloatOp::Abs => "fabs",
        }
    }
}
