//! MIR (Mid-level Intermediate Representation) Dumper
//!
//! This module provides functionality to dump MIR in a human-readable format
//! following the C11 compiler's specific conventions:
//! - Local variables: %0, %1, %tmp3
//! - Global variables: @g_var
//! - Basic blocks: bb0, bb1
//! - Constants: const 42, const null
//! - Types: i8, i16, i32, i64, u8, u16, u32, u64, f32, f64, ptr<T>

use std::fmt;
use std::fmt::Write;

use super::{
    BinaryFloatOp, CallTarget, ConstValueId, ConstValueKind, Global, GlobalId, LocalId, MirBlock, MirBlockId,
    MirFunction, MirFunctionId, MirLinkage, MirStmt, MirType, Operand, Place, Rvalue, Terminator, TypeId, UnaryFloatOp,
};
use crate::mir::MirProgram;

/// Configuration for MIR dump output
#[derive(Debug, Clone)]
pub(crate) struct MirDumpConfig {
    pub include_header: bool,
}

impl Default for MirDumpConfig {
    fn default() -> Self {
        MirDumpConfig { include_header: true }
    }
}

/// Main MIR dumper that generates human-readable MIR output
pub(crate) struct MirDumper<'a> {
    mir: &'a MirProgram,
    config: &'a MirDumpConfig,
}

impl<'a> MirDumper<'a> {
    /// Create a new MIR dumper
    pub(crate) fn new(mir: &'a MirProgram, config: &'a MirDumpConfig) -> Self {
        Self { mir, config }
    }

    /// Generate the complete MIR dump
    pub(crate) fn generate_mir_dump(&self) -> Result<String, fmt::Error> {
        let mut output = String::new();

        // Dump module header
        if self.config.include_header {
            writeln!(output, "; MIR Dump for Module 1")?;
            writeln!(output, "; Generated by Cendol C11 Compiler")?;
            writeln!(output)?;
        }

        // Dump type definitions
        self.dump_types(&mut output)?;
        writeln!(output)?;

        // Dump global variables first
        if !self.mir.globals.is_empty() {
            for global in self.mir.globals.iter() {
                self.dump_global(&mut output, global)?;
                writeln!(output)?;
            }
            writeln!(output)?;
        }

        // Dump all functions
        for func in self.mir.functions.iter() {
            self.dump_function(&mut output, func)?;
            writeln!(output)?;
        }

        Ok(output)
    }

    /// Dump a single function
    fn dump_function(&self, output: &mut String, func: &MirFunction) -> fmt::Result {
        // Function signature
        let fn_keyword = if matches!(func.linkage, MirLinkage::Import) {
            "extern fn"
        } else {
            "fn"
        };
        write!(output, "{} {}(", fn_keyword, func.name)?;

        // Dump parameters
        self.write_joined(output, &func.params, |out, &param_id| {
            if let Some(param) = self.mir.locals.get(param_id.index()) {
                write!(out, "%")?;
                if let Some(name) = &param.name {
                    write!(out, "{}", name)?;
                } else {
                    write!(out, "unnamed")?;
                }
                write!(out, ": ")?;
                self.write_type(out, param.type_id)
            } else {
                write!(out, "%param{}: ?", param_id.get())
            }
        })?;

        if func.is_variadic {
            if !func.params.is_empty() {
                self.write_comma(output)?;
            }
            write!(output, "...")?;
        }

        write!(output, ") -> ")?;
        self.write_type(output, func.return_type)?;

        // For extern functions, don't output any body
        if matches!(func.linkage, MirLinkage::Import) {
            writeln!(output)?;
            return Ok(());
        }

        writeln!(output)?;

        // Function body
        writeln!(output, "{{")?;

        // Dump locals section
        if !func.locals.is_empty() {
            writeln!(output, "  locals {{")?;
            for &local_id in &func.locals {
                if let Some(local) = self.mir.locals.get(local_id.index()) {
                    write!(output, "    ")?;
                    self.write_local(output, local_id)?;
                    write!(output, ": ")?;
                    self.write_type(output, local.type_id)?;
                    writeln!(output)?;
                }
            }
            writeln!(output, "  }}")?;
        }

        // Dump basic blocks
        for &block_id in &func.blocks {
            if let Some(block) = self.mir.blocks.get(block_id.index()) {
                self.dump_block(output, block_id, block)?;
            }
        }

        writeln!(output, "}}")
    }

    /// Dump all type definitions
    fn dump_types(&self, output: &mut String) -> fmt::Result {
        for (i, mir_type) in self.mir.module.types.iter().enumerate() {
            let type_id = TypeId::new((i + 1) as u32).unwrap();
            let type_index = self.get_type_index(type_id);
            write!(output, "type %t{} = ", type_index)?;
            self.write_type_inner(output, type_id, mir_type, true)?;
            writeln!(output)?;
        }
        Ok(())
    }

    /// Internal helper to format MIR types
    fn write_type_inner<W: fmt::Write>(
        &self,
        output: &mut W,
        type_id: TypeId,
        mir_type: &MirType,
        is_definition: bool,
    ) -> fmt::Result {
        match mir_type {
            MirType::Pointer { pointee } => {
                if is_definition {
                    let index = self.get_type_index(*pointee);
                    write!(output, "ptr<%t{}>", index)
                } else {
                    write!(output, "ptr<")?;
                    self.write_type(output, *pointee)?;
                    write!(output, ">")
                }
            }
            MirType::Array { element, size, .. } => {
                if is_definition {
                    let index = self.get_type_index(*element);
                    write!(output, "[{}]%t{}", size, index)
                } else {
                    write!(output, "[{}]", size)?;
                    self.write_type(output, *element)
                }
            }
            MirType::Function {
                return_type,
                params,
                is_variadic,
            } => {
                write!(output, "fn(")?;
                self.write_joined(output, params, |out, &p| {
                    if is_definition {
                        let index = self.get_type_index(p);
                        write!(out, "%t{}", index)
                    } else {
                        self.write_type(out, p)
                    }
                })?;
                if *is_variadic {
                    if !params.is_empty() {
                        self.write_comma(output)?;
                    }
                    write!(output, "...")?;
                }
                write!(output, ") -> ")?;
                if is_definition {
                    let index = self.get_type_index(*return_type);
                    write!(output, "%t{}", index)
                } else {
                    self.write_type(output, *return_type)
                }
            }
            MirType::Record {
                name,
                field_types,
                field_names,
                is_union,
                ..
            } => {
                if is_definition {
                    let kind = if *is_union { "union" } else { "struct" };
                    write!(output, "{} {} {{ ", kind, name)?;
                    let fields = field_names.iter().zip(field_types.iter());
                    self.write_joined(output, fields, |out, (fname, &fid)| {
                        let index = self.get_type_index(fid);
                        write!(out, "{}: %t{}", fname, index)
                    })?;
                    write!(output, " }}")
                } else {
                    let index = self.get_type_index(type_id);
                    write!(output, "%t{}", index)
                }
            }
            _ => write!(output, "{}", mir_type),
        }
    }

    /// Helper function to get type index from TypeId
    fn get_type_index(&self, type_id: TypeId) -> usize {
        // Fallback: assume sequential mapping
        (type_id.get() - 1) as usize
    }

    /// Dump a single global variable
    fn dump_global(&self, output: &mut String, global: &Global) -> fmt::Result {
        write!(output, "global @{}: ", global.name)?;
        self.write_type(output, global.type_id)?;
        if global.is_tls {
            write!(output, " (tls)")?;
        }

        if let Some(const_id) = global.initial_value {
            write!(output, " = ")?;
            if !self.write_string_literal_if_possible(output, global.name.as_str(), const_id)? {
                self.write_const(output, const_id)?;
            }
        }
        Ok(())
    }

    /// Dump a basic block
    fn dump_block(&self, output: &mut String, block_id: MirBlockId, block: &MirBlock) -> fmt::Result {
        writeln!(output)?;
        write!(output, "  ")?;
        self.write_block(output, block_id)?;
        writeln!(output, ":")?;

        // Dump statements in the block
        for &stmt_id in &block.statements {
            if let Some(stmt) = self.mir.statements.get(stmt_id.index()) {
                write!(output, "    ")?;
                self.dump_statement(output, stmt)?;
                writeln!(output)?;
            }
        }

        // Dump terminator (MUST be explicit)
        write!(output, "    ")?;
        self.dump_terminator(output, &block.terminator)?;
        writeln!(output)
    }

    /// Dump a statement
    fn dump_statement(&self, output: &mut String, stmt: &MirStmt) -> fmt::Result {
        match stmt {
            MirStmt::Assign(place, rvalue) => {
                self.write_place(output, place)?;
                write!(output, " = ")?;
                self.dump_rvalue(output, rvalue)
            }
            MirStmt::Call { target, args, dest } => {
                if let Some(place) = dest {
                    self.write_place(output, place)?;
                    write!(output, " = ")?;
                }
                write!(output, "call ")?;
                self.write_call_target(output, target)?;
                write!(output, "(")?;
                self.write_joined(output, args, |out, operand| self.write_operand(out, operand))?;
                write!(output, ")")
            }
            MirStmt::BuiltinVaStart(ap, last) => self.write_call(
                output,
                "va_start",
                &[&|out| self.write_place(out, ap), &|out| self.write_operand(out, last)],
            ),
            MirStmt::BuiltinVaEnd(ap) => self.write_call(output, "va_end", &[&|out| self.write_place(out, ap)]),
            MirStmt::BuiltinVaCopy(dst, src) => self.write_call(
                output,
                "va_copy",
                &[&|out| self.write_place(out, dst), &|out| self.write_place(out, src)],
            ),
            MirStmt::AtomicStore(ptr, val, order) => self.write_call(
                output,
                "atomic_store",
                &[
                    &|out| self.write_operand(out, ptr),
                    &|out| self.write_operand(out, val),
                    &|out| write!(out, "{:?}", order).map_err(Into::into),
                ],
            ),
            MirStmt::InlineAsm {
                template,
                outputs,
                inputs,
                clobbers,
                is_volatile,
            } => {
                let v = if *is_volatile { "volatile " } else { "" };
                write!(output, "asm {:?}({:?})", v, template)?;
                if !outputs.is_empty() || !inputs.is_empty() || !clobbers.is_empty() {
                    write!(output, " : ")?;
                    for (i, (c, p)) in outputs.iter().enumerate() {
                        if i > 0 {
                            write!(output, ", ")?;
                        }
                        write!(output, "{:?} ", c)?;
                        self.write_place(output, p)?;
                    }
                    write!(output, " : ")?;
                    for (i, (c, op)) in inputs.iter().enumerate() {
                        if i > 0 {
                            write!(output, ", ")?;
                        }
                        write!(output, "{:?} ", c)?;
                        self.write_operand(output, op)?;
                    }
                    write!(output, " : ")?;
                    for (i, c) in clobbers.iter().enumerate() {
                        if i > 0 {
                            write!(output, ", ")?;
                        }
                        write!(output, "{:?}", c)?;
                    }
                }
                Ok(())
            }
            MirStmt::BuiltinPrefetch { addr, rw, locality } => self.write_call(
                output,
                "prefetch",
                &[
                    &|out| self.write_operand(out, addr),
                    &|out| write!(out, "{}", rw),
                    &|out| write!(out, "{}", locality),
                ],
            ),
        }
    }

    /// Dump a terminator
    fn dump_terminator(&self, output: &mut String, terminator: &Terminator) -> fmt::Result {
        match terminator {
            Terminator::Goto(block_id) => {
                write!(output, "br ")?;
                self.write_block(output, *block_id)
            }
            Terminator::GotoIndirect(op) => {
                write!(output, "br_indirect ")?;
                self.write_operand(output, op)
            }
            Terminator::If(cond, then_block, else_block) => {
                write!(output, "cond_br ")?;
                self.write_operand(output, cond)?;
                self.write_comma(output)?;
                self.write_block(output, *then_block)?;
                self.write_comma(output)?;
                self.write_block(output, *else_block)
            }
            Terminator::Return(operand) => {
                write!(output, "return")?;
                if let Some(op) = operand {
                    write!(output, " ")?;
                    self.write_operand(output, op)?;
                }
                Ok(())
            }
            Terminator::Unreachable => write!(output, "unreachable"),
            Terminator::Trap => write!(output, "trap"),
        }
    }

    /// Convert MIR type to string representation
    fn write_type<W: fmt::Write>(&self, output: &mut W, type_id: TypeId) -> fmt::Result {
        if let Some(mir_type) = self.mir.types.get(type_id.index()) {
            self.write_type_inner(output, type_id, mir_type, false)
        } else {
            write!(output, "unknown_type_{}", type_id.get())
        }
    }

    /// Write a comma separator
    fn write_comma<W: fmt::Write>(&self, output: &mut W) -> fmt::Result {
        write!(output, ", ")
    }

    /// Write a call-style instruction formatting (e.g. instruction(arg1, arg2))
    fn write_call<W: fmt::Write>(
        &self,
        output: &mut W,
        name: &str,
        args: &[&dyn Fn(&mut W) -> fmt::Result],
    ) -> fmt::Result {
        write!(output, "{}(", name)?;
        for (i, arg) in args.iter().enumerate() {
            if i > 0 {
                self.write_comma(output)?;
            }
            arg(output)?;
        }
        write!(output, ")")
    }

    /// Write an iterator of items joined by commas
    fn write_joined<W: fmt::Write, I, F>(&self, output: &mut W, items: I, mut format_item: F) -> fmt::Result
    where
        I: IntoIterator,
        F: FnMut(&mut W, I::Item) -> fmt::Result,
    {
        let mut first = true;
        for item in items {
            if !first {
                self.write_comma(output)?;
            }
            first = false;
            format_item(output, item)?;
        }
        Ok(())
    }

    /// Convert local ID to string representation
    fn write_local<W: fmt::Write>(&self, output: &mut W, local_id: LocalId) -> fmt::Result {
        write!(output, "%")?;
        if let Some(local) = self.mir.locals.get(local_id.index())
            && let Some(name) = &local.name
        {
            write!(output, "{}", name)
        } else {
            write!(output, "{}", local_id.get())
        }
    }

    /// Convert global ID to string representation
    fn write_global<W: fmt::Write>(&self, output: &mut W, global_id: GlobalId) -> fmt::Result {
        if let Some(global) = self.mir.globals.get(global_id.index()) {
            write!(output, "@{}", global.name)
        } else {
            write!(output, "@global_{}", global_id.get())
        }
    }

    /// Convert block ID to string representation
    fn write_block<W: fmt::Write>(&self, output: &mut W, block_id: MirBlockId) -> fmt::Result {
        write!(output, "bb{}", block_id.get())
    }

    /// Convert function ID to string representation
    fn write_function_name<W: fmt::Write>(&self, output: &mut W, func_id: MirFunctionId) -> fmt::Result {
        if let Some(func) = self.mir.functions.get(func_id.index()) {
            write!(output, "{}", func.name)
        } else {
            write!(output, "func_{}", func_id.get())
        }
    }

    /// Convert call target to string representation
    fn write_call_target<W: fmt::Write>(&self, output: &mut W, call_target: &CallTarget) -> fmt::Result {
        match call_target {
            CallTarget::Direct(func_id) => self.write_function_name(output, *func_id),
            CallTarget::Indirect(operand) => {
                write!(output, "*")?;
                self.write_operand(output, operand)
            }
        }
    }

    /// Try to format a constant as a string literal if applicable
    fn write_string_literal_if_possible<W: fmt::Write>(
        &self,
        output: &mut W,
        name: &str,
        const_id: ConstValueId,
    ) -> Result<bool, fmt::Error> {
        if !name.starts_with(".L.str") {
            return Ok(false);
        }

        let Some(const_value) = self.mir.constants.get(const_id.index()) else {
            return Ok(false);
        };
        let ConstValueKind::ArrayLiteral(elements) = &const_value.kind else {
            return Ok(false);
        };

        let mut bytes = Vec::with_capacity(elements.len());
        for &id in elements {
            match self.mir.constants.get(id.index()).map(|c| &c.kind) {
                Some(ConstValueKind::Int(val)) => bytes.push(*val as u8),
                _ => return Ok(false),
            }
        }

        write!(output, "const \"")?;
        for &byte in &bytes {
            if byte == 0 {
                break;
            }
            match byte {
                b'\n' => write!(output, "\\n")?,
                b'\r' => write!(output, "\\r")?,
                b'\t' => write!(output, "\\t")?,
                b'\\' => write!(output, "\\\\")?,
                b'"' => write!(output, "\\\"")?,
                32..=126 => write!(output, "{}", byte as char)?,
                _ => write!(output, "\\x{:02x}", byte)?,
            }
        }
        write!(output, "\"")?;
        Ok(true)
    }

    /// Convert constant ID to string representation
    fn write_const<W: fmt::Write>(&self, output: &mut W, const_id: ConstValueId) -> fmt::Result {
        let Some(const_value) = self.mir.constants.get(const_id.index()) else {
            return write!(output, "const unknown_{}", const_id.get());
        };

        write!(output, "const ")?;
        match &const_value.kind {
            ConstValueKind::Int(val) => write!(output, "{}", val),
            ConstValueKind::Float(val) => write!(output, "{}", val),
            ConstValueKind::Bool(val) => write!(output, "{}", val),
            ConstValueKind::Null => write!(output, "null"),
            ConstValueKind::Zero => write!(output, "zero"),
            ConstValueKind::StructLiteral(fields) => {
                write!(output, "struct_literal {{ ")?;
                self.write_joined(output, fields, |out, (field_idx, field_const_id)| {
                    write!(out, "{}: ", field_idx)?;
                    self.write_const(out, *field_const_id)
                })?;
                write!(output, " }}")
            }
            ConstValueKind::ArrayLiteral(elements) => {
                write!(output, "array_literal [")?;
                self.write_joined(output, elements, |out, &element_const_id| {
                    self.write_const(out, element_const_id)
                })?;
                write!(output, "]")
            }
            ConstValueKind::GlobalAddress(global_id, addend) => {
                self.write_global(output, *global_id)?;
                if *addend != 0 {
                    write!(output, "+{}", addend)
                } else {
                    Ok(())
                }
            }
            ConstValueKind::FunctionAddress(func_id) => self.write_function_name(output, *func_id),
        }
    }

    /// Convert place to string representation
    fn write_place<W: fmt::Write>(&self, output: &mut W, place: &Place) -> fmt::Result {
        match place {
            Place::Local(local_id) => self.write_local(output, *local_id),
            Place::Deref(operand) => self.write_call(output, "deref", &[&|out| self.write_operand(out, operand)]),
            Place::Global(global_id) => self.write_global(output, *global_id),
            Place::StructField(base_place, field_idx, bit_info) => {
                self.write_place(output, base_place)?;
                write!(output, ".field_{}", field_idx)?;
                if let Some(b) = bit_info {
                    write!(output, " (bit:{}:{})", b.offset, b.width)?;
                }
                Ok(())
            }
            Place::ArrayIndex(base_place, index) => {
                self.write_place(output, base_place)?;
                write!(output, "[")?;
                self.write_operand(output, index)?;
                write!(output, "]")
            }
        }
    }

    /// Convert operand to string representation
    fn write_operand<W: fmt::Write>(&self, output: &mut W, operand: &Operand) -> fmt::Result {
        match operand {
            Operand::Copy(place) => self.write_place(output, place),
            Operand::Constant(const_id) => self.write_const(output, *const_id),
            Operand::AddressOf(place) => self.write_call(output, "addr_of", &[&|out| self.write_place(out, place)]),
            Operand::Cast(type_id, operand) => {
                write!(output, "cast<")?;
                self.write_type(output, *type_id)?;
                write!(output, ">(")?;
                self.write_operand(output, operand)?;
                write!(output, ")")
            }
        }
    }

    /// Dump an rvalue (for use in assignments)
    fn dump_rvalue(&self, output: &mut String, rvalue: &Rvalue) -> fmt::Result {
        match rvalue {
            Rvalue::Use(operand) => self.write_operand(output, operand),
            Rvalue::BinaryIntOp(op, left, right) => {
                self.write_operand(output, left)?;
                write!(output, " {} ", self.binary_int_op_to_string(op))?;
                self.write_operand(output, right)
            }
            Rvalue::BinaryFloatOp(op, left, right) => {
                self.write_operand(output, left)?;
                write!(output, " {} ", self.binary_float_op_to_string(op))?;
                self.write_operand(output, right)
            }
            Rvalue::UnaryIntOp(op, operand) => {
                write!(output, "{} ", self.unary_int_op_to_string(op))?;
                self.write_operand(output, operand)
            }
            Rvalue::UnaryFloatOp(op, operand) => {
                write!(output, "{} ", self.unary_float_op_to_string(op))?;
                self.write_operand(output, operand)
            }
            Rvalue::PtrAdd(base, offset) => self.write_call(
                output,
                "ptradd",
                &[&|out| self.write_operand(out, base), &|out| {
                    self.write_operand(out, offset)
                }],
            ),
            Rvalue::PtrSub(base, offset) => self.write_call(
                output,
                "ptrsub",
                &[&|out| self.write_operand(out, base), &|out| {
                    self.write_operand(out, offset)
                }],
            ),
            Rvalue::PtrDiff(left, right) => self.write_call(
                output,
                "ptrdiff",
                &[&|out| self.write_operand(out, left), &|out| {
                    self.write_operand(out, right)
                }],
            ),
            Rvalue::StructLiteral(fields) => {
                write!(output, "struct{{")?;
                self.write_joined(output, fields, |out, (idx, op)| {
                    write!(out, "{}: ", idx)?;
                    self.write_operand(out, op)
                })?;
                write!(output, "}}")
            }
            Rvalue::ArrayLiteral(elements) => {
                write!(output, "[")?;
                self.write_joined(output, elements, |out, op| self.write_operand(out, op))?;
                write!(output, "]")
            }
            Rvalue::BuiltinVaArg(ap, ty) => self.write_call(
                output,
                "va_arg",
                &[&|out| self.write_place(out, ap), &|out| self.write_type(out, *ty)],
            ),
            Rvalue::BuiltinFrameAddress(level) => {
                self.write_call(output, "frame_address", &[&|out| write!(out, "{}", level)])
            }
            Rvalue::AtomicLoad(ptr, order) => self.write_call(
                output,
                "atomic_load",
                &[&|out| self.write_operand(out, ptr), &|out| write!(out, "{:?}", order)],
            ),
            Rvalue::AtomicExchange(ptr, val, order) => self.write_call(
                output,
                "atomic_xchg",
                &[
                    &|out| self.write_operand(out, ptr),
                    &|out| self.write_operand(out, val),
                    &|out| write!(out, "{:?}", order),
                ],
            ),
            Rvalue::AtomicCompareExchange(ptr, expected, desired, weak, success, failure) => self.write_call(
                output,
                "atomic_cmpxchg",
                &[
                    &|out| self.write_operand(out, ptr),
                    &|out| self.write_operand(out, expected),
                    &|out| self.write_operand(out, desired),
                    &|out| write!(out, "{}", weak),
                    &|out| write!(out, "{:?}", success),
                    &|out| write!(out, "{:?}", failure),
                ],
            ),
            Rvalue::AtomicFetchOp(op, ptr, val, order) => {
                let name = format!("atomic_fetch_{}", self.binary_int_op_to_string(op));
                self.write_call(
                    output,
                    &name,
                    &[
                        &|out| self.write_operand(out, ptr),
                        &|out| self.write_operand(out, val),
                        &|out| write!(out, "{:?}", order),
                    ],
                )
            }
            Rvalue::BuiltinOverflow(op, lhs, rhs, res_ptr, ty) => {
                let name = format!("{}_overflow", self.binary_int_op_to_string(op));
                self.write_call(
                    output,
                    &name,
                    &[
                        &|out| self.write_operand(out, lhs),
                        &|out| self.write_operand(out, rhs),
                        &|out| self.write_operand(out, res_ptr),
                        &|out| write!(out, "{:?}", ty),
                    ],
                )
            }
            Rvalue::LabelAddr(block_id) => {
                write!(output, "&&")?;
                self.write_block(output, *block_id)
            }
        }
    }

    /// Convert integer binary operation to string representation
    fn binary_int_op_to_string(&self, op: &super::BinaryIntOp) -> &'static str {
        match op {
            super::BinaryIntOp::Add => "+",
            super::BinaryIntOp::Sub => "-",
            super::BinaryIntOp::Mul => "*",
            super::BinaryIntOp::Div => "/",
            super::BinaryIntOp::Mod => "%",
            super::BinaryIntOp::BitAnd => "&",
            super::BinaryIntOp::BitOr => "|",
            super::BinaryIntOp::BitXor => "^",
            super::BinaryIntOp::LShift => "<<",
            super::BinaryIntOp::RShift => ">>",
            super::BinaryIntOp::Eq => "==",
            super::BinaryIntOp::Ne => "!=",
            super::BinaryIntOp::Lt => "<",
            super::BinaryIntOp::Le => "<=",
            super::BinaryIntOp::Gt => ">",
            super::BinaryIntOp::Ge => ">=",
        }
    }

    /// Convert integer unary operation to string representation
    fn unary_int_op_to_string(&self, op: &super::UnaryIntOp) -> &'static str {
        match op {
            super::UnaryIntOp::Neg => "-",
            super::UnaryIntOp::BitwiseNot => "~",
            super::UnaryIntOp::LogicalNot => "!",
            super::UnaryIntOp::Popcount => "popcount",
            super::UnaryIntOp::Clz => "clz",
            super::UnaryIntOp::Ctz => "ctz",
            super::UnaryIntOp::Bswap16 => "bswap16",
            super::UnaryIntOp::Bswap32 => "bswap32",
            super::UnaryIntOp::Bswap64 => "bswap64",
            super::UnaryIntOp::Ffs => "ffs",
        }
    }

    /// Convert floating-point binary operation to string representation
    fn binary_float_op_to_string(&self, op: &BinaryFloatOp) -> &'static str {
        match op {
            BinaryFloatOp::Add => "fadd",
            BinaryFloatOp::Sub => "fsub",
            BinaryFloatOp::Mul => "fmul",
            BinaryFloatOp::Div => "fdiv",
            BinaryFloatOp::Eq => "feq",
            BinaryFloatOp::Ne => "fne",
            BinaryFloatOp::Lt => "flt",
            BinaryFloatOp::Le => "fle",
            BinaryFloatOp::Gt => "fgt",
            BinaryFloatOp::Ge => "fge",
        }
    }

    /// Convert floating-point unary operation to string representation
    fn unary_float_op_to_string(&self, op: &UnaryFloatOp) -> &'static str {
        match op {
            UnaryFloatOp::Neg => "fneg",
            UnaryFloatOp::Abs => "fabs",
            UnaryFloatOp::IsNegative => "is_negative",
        }
    }
}
