// Auto-generated by tools/generate_types
// DO NOT EDIT MANUALLY

impl TypeId {
    pub const VOID: TypeId = TypeId::from_parts(0, TypeId::FLAG_CANONICAL);
    pub const BOOL: TypeId = TypeId::from_parts(1, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_UNSIGNED);
    pub const CHAR: TypeId = TypeId::from_parts(2, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
    pub const SHORT: TypeId = TypeId::from_parts(3, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
    pub const INT: TypeId = TypeId::from_parts(4, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
    pub const LONG: TypeId = TypeId::from_parts(5, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
    pub const FLOAT: TypeId = TypeId::from_parts(6, TypeId::FLAG_CANONICAL|TypeId::FLAG_FLOATING);
    pub const DOUBLE: TypeId = TypeId::from_parts(7, TypeId::FLAG_CANONICAL|TypeId::FLAG_FLOATING);
    pub const VOID_PTR: TypeId = TypeId::from_parts(8, TypeId::FLAG_CANONICAL | TypeId::FLAG_POINTER);
    pub const BOOL_PTR: TypeId = TypeId::from_parts(9, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_UNSIGNED | TypeId::FLAG_POINTER);
    pub const CHAR_PTR: TypeId = TypeId::from_parts(10, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED | TypeId::FLAG_POINTER);
    pub const SHORT_PTR: TypeId = TypeId::from_parts(11, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED | TypeId::FLAG_POINTER);
    pub const INT_PTR: TypeId = TypeId::from_parts(12, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED | TypeId::FLAG_POINTER);
    pub const LONG_PTR: TypeId = TypeId::from_parts(13, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED | TypeId::FLAG_POINTER);
    pub const FLOAT_PTR: TypeId = TypeId::from_parts(14, TypeId::FLAG_CANONICAL|TypeId::FLAG_FLOATING | TypeId::FLAG_POINTER);
    pub const DOUBLE_PTR: TypeId = TypeId::from_parts(15, TypeId::FLAG_CANONICAL|TypeId::FLAG_FLOATING | TypeId::FLAG_POINTER);

}

impl TypeTable {
    pub fn new_with_builtins() -> Self {
        let mut table = TypeTable {
            types: Vec::new(),
            map: HashMap::new(),
        };

        let push = |kind: TypeKind, tbl: &mut TypeTable| {
            let idx = tbl.types.len() as u16;
            tbl.map.insert(kind.clone(), idx);
            tbl.types.push(kind);
        };
        push(TypeKind::Void, &mut table); // 0
        push(TypeKind::Bool, &mut table); // 1
        push(TypeKind::Char, &mut table); // 2
        push(TypeKind::Short, &mut table); // 3
        push(TypeKind::Int, &mut table); // 4
        push(TypeKind::Long, &mut table); // 5
        push(TypeKind::Float, &mut table); // 6
        push(TypeKind::Double, &mut table); // 7

        let void_id = TypeId::from_parts(0, TypeId::FLAG_CANONICAL);
        push(TypeKind::Pointer(void_id), &mut table); // 8
        let bool_id = TypeId::from_parts(1, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_UNSIGNED);
        push(TypeKind::Pointer(bool_id), &mut table); // 9
        let char_id = TypeId::from_parts(2, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
        push(TypeKind::Pointer(char_id), &mut table); // 10
        let short_id = TypeId::from_parts(3, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
        push(TypeKind::Pointer(short_id), &mut table); // 11
        let int_id = TypeId::from_parts(4, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
        push(TypeKind::Pointer(int_id), &mut table); // 12
        let long_id = TypeId::from_parts(5, TypeId::FLAG_CANONICAL|TypeId::FLAG_INTEGER|TypeId::FLAG_SIGNED);
        push(TypeKind::Pointer(long_id), &mut table); // 13
        let float_id = TypeId::from_parts(6, TypeId::FLAG_CANONICAL|TypeId::FLAG_FLOATING);
        push(TypeKind::Pointer(float_id), &mut table); // 14
        let double_id = TypeId::from_parts(7, TypeId::FLAG_CANONICAL|TypeId::FLAG_FLOATING);
        push(TypeKind::Pointer(double_id), &mut table); // 15
        table
    }
}
