pub mod codegen_abi;
pub mod codegen_abi_compat;
pub mod codegen_alignas;
mod codegen_atomic;
pub mod codegen_basics;
pub mod codegen_bswap;
pub mod codegen_calls;
pub mod codegen_common;
pub mod codegen_large_array;
pub mod codegen_tls;

pub mod codegen_bitfield;
pub mod codegen_float_to_int_oob;
pub mod codegen_global_redeclaration;
pub mod codegen_offsetof;
pub mod codegen_runtime;
pub mod codegen_structs;
pub mod codegen_switch;
pub mod codegen_variadic;

pub mod driver_ast_dumper;
pub mod driver_source_manager;

pub mod pp_common;
pub mod pp_conditionals;
pub mod pp_directives;
pub mod pp_features;
pub mod pp_includes;
pub mod pp_internal;
pub mod pp_lexical;
pub mod pp_macros;

pub mod semantic_arrays;
pub mod semantic_auto_type;
pub mod semantic_builtin_choose_expr;
pub mod semantic_builtin_constant_p;
pub mod semantic_builtin_trap;
pub mod semantic_builtin_types_compatible;
pub mod semantic_builtin_unreachable;
pub mod semantic_builtins;
pub mod semantic_builtins_bitwise;
pub mod semantic_conflicting_type_spec;
pub mod semantic_control_flow;
pub mod semantic_deref_check;
pub mod semantic_empty_decl;
pub mod semantic_enums;
pub mod semantic_expr;
pub mod semantic_float_init;
pub mod semantic_functions;
pub mod semantic_init;
pub mod semantic_scope;
pub mod semantic_typeof;
pub mod semantic_types;

pub mod semantic_common;
pub mod semantic_const_eval;
pub mod semantic_lowering;
pub mod semantic_mir;
pub mod semantic_negative;
pub mod semantic_regr_bitfield_promotion;
pub mod semantic_regr_unary_promotion;
pub mod semantic_unary_coverage;
pub mod semantic_validation;

pub mod parser_decl;
pub mod parser_declarator_coverage;
pub mod parser_expr;
pub mod parser_lexical;
pub mod parser_stmt;
pub mod parser_types;
pub mod parser_utils;

pub mod codegen_ternary_array_size;
pub mod parser_gcc_extensions;
pub mod parser_regr_hang;
pub mod parser_type_spec_coverage;
pub mod parser_typeof;

pub mod guardian_increment_completeness;
pub mod guardian_pointer_arithmetic_completeness;
pub mod semantic_alignment;
pub mod semantic_composite;
pub mod test_utils;

pub mod ast_dumper_coverage;

pub mod codegen_bool_cast;
pub mod codegen_builtin_choose_expr;
pub mod codegen_builtin_constant_p;
pub mod codegen_builtin_unreachable;
pub mod codegen_builtins_bitwise;
pub mod codegen_cast_init;
pub mod codegen_func_ptr_global;
pub mod codegen_regr;
pub mod codegen_store_truncation;
pub mod driver_defines;
pub mod guardian_alias_completeness;
pub mod guardian_array_init_bounds;
pub mod guardian_array_init_string;
pub mod guardian_bitfield_constraints;
pub mod guardian_compound_literal_constraints;
pub mod guardian_generic_bitfield;
pub mod guardian_generic_compatibility;
pub mod guardian_noreturn_switch;
pub mod guardian_offsetof;
pub mod guardian_relational_pointer_constraints;
pub mod guardian_sizeof_alignof;
pub mod guardian_ternary_pointer_constraints;
pub mod mir_dumper_coverage;
pub mod mir_gen_compound_assignment;
pub mod mir_gen_function_address;
pub mod mir_gen_function_calls;
pub mod mir_gen_sizeof;
pub mod mir_unit;
pub mod mir_validation;
pub mod parser_attributes_declarator;
pub mod parser_builder_coverage;
pub mod parser_expect_name_coverage;
pub mod parser_typedef_shadowing;
pub mod pp_dumper_coverage;
pub mod pp_macro_nested;
pub mod pragma_pack;
pub mod semantic_assignment_coverage;
pub mod semantic_atomic;
pub mod semantic_bitfield_init;
pub mod semantic_brace_elision;
pub mod semantic_caserange;
pub mod semantic_complex_types;
pub mod semantic_const_recursive;
mod semantic_conversions;
pub mod semantic_generic;
pub mod semantic_goto_vla;
pub mod semantic_implicit_builtins;
pub mod semantic_integer_literals;
pub mod semantic_issue_test;
mod semantic_label_duplicate;
mod semantic_label_goto;
pub mod semantic_mir_const_global;
pub mod semantic_noreturn;
pub mod semantic_offsetof;
pub mod semantic_parsed_declarator_coverage;
pub mod semantic_parsed_types_coverage;
pub mod semantic_regr_real_imag;
pub mod semantic_regr_struct_init_in_array;
pub mod semantic_return_check;
pub mod semantic_return_local_address;
pub mod semantic_scope_invariants;
pub mod semantic_shift_float;
pub mod semantic_sizeof_vla;
pub mod semantic_static_assert;
pub mod semantic_valist;

pub mod regr_bitfield_assign_eval;
pub mod regr_fp_const_eval;
pub mod regr_init_range;
pub mod regr_struct_bitfield;
pub mod regr_vla_sizeof;
pub mod regr_vla_static;
